# Generated by Django 3.2.16 on 2023-02-08 15:24

from django.db import migrations, models
import eda_invoices.uploads.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('short_uuid', models.CharField(editable=False, max_length=29, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data_file', models.FileField(upload_to=eda_invoices.uploads.models.upload_data_file)),
                ('email', models.EmailField(max_length=254)),
                ('bbc_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('metering_points', models.JSONField(blank=True, default=list, null=True)),
                ('sender', models.JSONField(blank=True, default=dict, null=True)),
                ('customers', models.JSONField(blank=True, default=list, null=True)),
                ('tariffs', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
