# Generated by Django 3.2.16 on 2022-12-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='email',
            field=models.EmailField(default='john.doe@example.org', max_length=254),
            preserve_default=False,
        ),
    ]
