# Generated by Django 3.2.16 on 2022-12-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='short_uuid',
            field=models.CharField(editable=False, max_length=29, unique=True),
        ),
    ]
