# Generated by Django 3.2.16 on 2023-02-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20230206_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userupload',
            name='conf_file',
        ),
        migrations.AlterField(
            model_name='userupload',
            name='customers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='metering_points',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='sender',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='tariffs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
