# Generated by Django 3.2.16 on 2023-02-08 15:24

from django.db import migrations, models
import django.db.models.deletion
import eda_invoices.invoices.json_encoder
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('short_uuid', models.CharField(editable=False, max_length=29, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, default=dict, encoder=eda_invoices.invoices.json_encoder.MyJSONEncoder)),
                ('user_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploads.userupload')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
