# Generated by Django 3.2.16 on 2023-02-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='data',
            new_name='invoice_data',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='metering_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sender',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
