# Generated by Django 3.2.16 on 2022-12-26 21:06

from django.db import migrations, models
import eda_invoices.invoices.json_encoder


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='data',
            field=models.JSONField(blank=True, default=dict, encoder=eda_invoices.invoices.json_encoder.MyJSONEncoder),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='short_uuid',
            field=models.CharField(editable=False, max_length=29, unique=True),
        ),
    ]
