# Generated by Django 3.2.16 on 2023-02-09 14:59

from django.db import migrations, models
import eda_invoices.invoices.json_encoder


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20230209_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_data',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stops_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.JSONField(blank=True, default=dict, encoder=eda_invoices.invoices.json_encoder.MyJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='metering_data',
            field=models.JSONField(blank=True, default=dict, encoder=eda_invoices.invoices.json_encoder.MyJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sender',
            field=models.JSONField(blank=True, default=dict, encoder=eda_invoices.invoices.json_encoder.MyJSONEncoder, null=True),
        ),
    ]
